--- Sentencias SQL para la creación del esquema de parranderos
--- Las tablas tienen prefijo A_ para facilitar su acceso desde SQL Developer

-- Eliminar el contenido de todas las tablas de la base de datos
delete from REGISTRANVEHICULO;
delete from REGISTRANCARNET;
delete from VEHICULO;
delete from EMPLEADO;
delete from CARNET;
delete from TIPOCARNET;
delete from LECTOR;
delete from TIPOLECTOR;
delete from ZONACIRCULACION;
delete from LOCALCOMERCIAL;
delete from TIPOLOCAL;
delete from PARQUEADERO;
delete from BANO;
delete from ASCENSOR;
delete from CAPACIDADNORMAL;
delete from AREA;
delete from CENTROCOMERCIAL;
delete from VISITANTE;
delete from LECTOR;
delete from TIPOVISITANTE;
delete from HORARIO;
delete from ADMINISTRADOR;
delete from ADMINISTRADORLOCAL;

commit;

-- Eliminar todas las tablas de la base de datos
DROP TABLE "AREA" CASCADE CONSTRAINTS;
DROP TABLE "ASCENSOR" CASCADE CONSTRAINTS;
DROP TABLE "BANO" CASCADE CONSTRAINTS;
DROP TABLE "CAPACIDADNORMAL" CASCADE CONSTRAINTS;
DROP TABLE "CARNET" CASCADE CONSTRAINTS;
DROP TABLE "CENTROCOMERCIAL" CASCADE CONSTRAINTS;
DROP TABLE "DOMICILIARIO" CASCADE CONSTRAINTS;
DROP TABLE "EMPLEADO" CASCADE CONSTRAINTS;
DROP TABLE "HORARIO" CASCADE CONSTRAINTS;
DROP TABLE "LECTOR" CASCADE CONSTRAINTS;
DROP TABLE "LOCALCOMERCIAL" CASCADE CONSTRAINTS;
DROP TABLE "ADMINISTRADOR" CASCADE CONSTRAINTS;
DROP TABLE "ADMINISTRADORLOCAL" CASCADE CONSTRAINTS;
DROP TABLE "PARQUEADERO" CASCADE CONSTRAINTS;
DROP TABLE "REGISTRANCARNET" CASCADE CONSTRAINTS;
DROP TABLE "REGISTRANVEHICULO" CASCADE CONSTRAINTS;
DROP TABLE "TIPOCARNET" CASCADE CONSTRAINTS;
DROP TABLE "TIPOLECTOR" CASCADE CONSTRAINTS;
DROP TABLE "TIPOLOCAL" CASCADE CONSTRAINTS;
DROP TABLE "TIPOVISITANTE" CASCADE CONSTRAINTS;
DROP TABLE "VEHICULO" CASCADE CONSTRAINTS;
DROP TABLE "VISITANTE" CASCADE CONSTRAINTS;
DROP TABLE "ZONACIRCULACION" CASCADE CONSTRAINTS;

-- Eliminar todas las secuencias de la base de datos
DROP SEQUENCE horario_sequence;
DROP SEQUENCE capacidadNormal_sequence;
DROP SEQUENCE area_sequence;
DROP SEQUENCE tipoLocal_sequence;
DROP SEQUENCE tipoCarnet_sequence;
DROP SEQUENCE tipoLector_sequence;
DROP SEQUENCE tipoVisitante_sequence;
COMMIT;
