--Horario de apertura y cierre por local
SELECT AUX1.*, AUX2.HORACIERRE, AUX2.MINUTOCIERRE
FROM
(
    SELECT LOCALCOMERCIAL.ACTIVO, HORARIO.HORA AS HORAAPERTURA, HORARIO.MINUTO AS MINUTOAPERTURA
    FROM LOCALCOMERCIAL
    JOIN TIPOLOCAL
    ON LOCALCOMERCIAL.TIPOLOCAL = TIPOLOCAL.ID
    JOIN HORARIO
    ON TIPOLOCAL.HORAAPERTURA = HORARIO.ID
    WHERE LOCALCOMERCIAL.NOMBRE = 'LC103'
) AUX1
JOIN
(
    SELECT LOCALCOMERCIAL.IDENTIFICADOR, HORARIO.HORA AS HORACIERRE, HORARIO.MINUTO AS MINUTOCIERRE
    FROM LOCALCOMERCIAL
    JOIN TIPOLOCAL
    ON LOCALCOMERCIAL.TIPOLOCAL = TIPOLOCAL.ID
    JOIN HORARIO
    ON TIPOLOCAL.HORACIERRE = HORARIO.ID
) AUX2
ON AUX1.IDENTIFICADOR = AUX2.IDENTIFICADOR;


--Horario de apertura y cierre por local
SELECT AUX1.*, AUX2.HORALIMITE, AUX2.MINUTOLIMITE
FROM
(
    SELECT VISITANTE.IDENTIFICACION, HORARIO.HORA AS HORAINICIO, HORARIO.MINUTO AS MINUTOINICIO
    FROM VISITANTE
    JOIN TIPOVISITANTE
    ON VISITANTE.TIPO = TIPOVISITANTE.ID
    JOIN HORARIO
    ON TIPOVISITANTE.HORAINICIO = HORARIO.ID
    WHERE VISITANTE.IDENTIFICACION = '3757003542'
) AUX1
JOIN
(
    SELECT VISITANTE.IDENTIFICACION, HORARIO.HORA AS HORALIMITE, HORARIO.MINUTO AS MINUTOLIMITE
    FROM VISITANTE
    JOIN TIPOVISITANTE
    ON VISITANTE.TIPO = TIPOVISITANTE.ID
    JOIN HORARIO
    ON TIPOVISITANTE.HORALIMITE = HORARIO.ID
) AUX2
ON AUX1.IDENTIFICACION = AUX2.IDENTIFICACION;

--RFC1 - MOSTRAR TODOS LOS VISITANTES ATENDIDOS POR UN ESTABLECIMIENTO EN UN RANGO DE FECHAS

SELECT DISTINCT VISITANTE.*
FROM LECTOR
JOIN
    (
        SELECT IDLECTOR, IDVISITANTE
        FROM REGISTRANCARNET
        WHERE FECHA BETWEEN TO_DATE('2019/04/24','yyyy/mm/dd') AND TO_DATE('2020/11/09','yyyy/mm/dd')
    ) INF_VISITAS
ON INF_VISITAS.IDLECTOR = LECTOR.ID
JOIN VISITANTE
ON INF_VISITAS.IDVISITANTE = VISITANTE.IDENTIFICACION
WHERE LECTOR.IDLOCALCOMERCIAL = 'LC104';

--RFC1 - MOSTRAR TODOS LOS VISITANTES ATENDIDOS POR UN ESTABLECIMIENTO EN UNA FECHA

SELECT DISTINCT VISITANTE.*
FROM LECTOR
JOIN
    (
        SELECT IDLECTOR, IDVISITANTE
        FROM REGISTRANCARNET
        WHERE FECHA =  TO_DATE('2019/04/24','yyyy/mm/dd')
    ) INF_VISITAS
ON INF_VISITAS.IDLECTOR = LECTOR.ID
JOIN VISITANTE
ON INF_VISITAS.IDVISITANTE = VISITANTE.IDENTIFICACION
WHERE LECTOR.IDLOCALCOMERCIAL = 'LC104';

--RFC1 - MOSTRAR TODOS LOS VISITANTES ATENDIDOS POR UN ESTABLECIMIENTO EN UN RANGO DE HORAS

SELECT VISITANTE.*
FROM LECTOR
JOIN
    (
        SELECT IDLECTOR, IDVISITANTE
        FROM HORARIO
        JOIN REGISTRANCARNET
        ON HORARIO.ID = REGISTRANCARNET.HORAENTRADA
        WHERE FECHA =  TO_DATE('2020/07/19','yyyy/mm/dd')
        AND (HORA BETWEEN 12 AND 16) OR (HORA = 12 AND MINUTO >= 36) OR  (HORA = 16 AND MINUTO <= 32)
    ) INF_VISITAS
ON INF_VISITAS.IDLECTOR = LECTOR.ID
JOIN VISITANTE
ON INF_VISITAS.IDVISITANTE = VISITANTE.IDENTIFICACION
WHERE LECTOR.IDLOCALCOMERCIAL = 'LC104';



--RFC2 - MOSTRAR LOS 20 ESTABLECIMIENTOS MÁS POPULARES (MÁS VISITADOS) EN UNA FECHA

SELECT LOCALCOMERCIAL.*
FROM LECTOR
JOIN 
    (SELECT IDLECTOR, NUM_VISITAS, DENSE_RANK() OVER (ORDER BY NUM_VISITAS DESC) RANK
    FROM
        (SELECT IDLECTOR, COUNT(*) AS NUM_VISITAS
        FROM REGISTRANCARNET
        WHERE FECHA =  TO_DATE('2019/07/19','yyyy/mm/dd')
        GROUP BY IDLECTOR)
    ) AUX
ON AUX.IDLECTOR = LECTOR.ID
JOIN LOCALCOMERCIAL
ON LECTOR.IDLOCALCOMERCIAL = LOCALCOMERCIAL.IDENTIFICADOR
WHERE RANK <= 20;

--RFC2 - MOSTRAR LOS 20 ESTABLECIMIENTOS MÁS POPULARES (MÁS VISITADOS) EN UN RANGO DE FECHAS

SELECT LOCALCOMERCIAL.*, NUM_VISITAS
FROM LECTOR
JOIN 
    (SELECT IDLECTOR, NUM_VISITAS, DENSE_RANK() OVER (ORDER BY NUM_VISITAS DESC) RANK
    FROM
        (SELECT IDLECTOR, COUNT(*) AS NUM_VISITAS
        FROM REGISTRANCARNET
        WHERE FECHA BETWEEN TO_DATE('2018/04/24','yyyy/mm/dd') AND TO_DATE('2021/12/09','yyyy/mm/dd')
        GROUP BY IDLECTOR)
    ) AUX
ON AUX.IDLECTOR = LECTOR.ID
JOIN LOCALCOMERCIAL
ON LECTOR.IDLOCALCOMERCIAL = LOCALCOMERCIAL.IDENTIFICADOR
WHERE RANK <= 20
ORDER BY NUM_VISITAS DESC;

--RFC2 - MOSTRAR LOS 20 ESTABLECIMIENTOS MÁS POPULARES (MÁS VISITADOS) EN UN RANGO DE HORAS

SELECT LOCALCOMERCIAL.*
FROM LECTOR
JOIN 
    (SELECT DISTINCT REGISTRANCARNET.IDLECTOR, NUM_VISITAS, DENSE_RANK() OVER (ORDER BY INF_VISITAS.NUM_VISITAS DESC) AS RANK
    FROM
        (
            SELECT IDLECTOR, COUNT(*) AS NUM_VISITAS
            FROM REGISTRANCARNET
            WHERE FECHA =  TO_DATE('2019/07/19','yyyy/mm/dd')
            GROUP BY IDLECTOR
        ) INF_VISITAS
    JOIN REGISTRANCARNET
    ON INF_VISITAS.IDLECTOR = REGISTRANCARNET.IDLECTOR
    JOIN HORARIO
    ON REGISTRANCARNET.HORAENTRADA = HORARIO.ID
    WHERE (HORA BETWEEN 14 AND 18) OR (HORA = 14 AND MINUTO >= 14) OR (HORA = 18 AND MINUTO <= 10)
    ) AUX
ON AUX.IDLECTOR = LECTOR.ID
JOIN LOCALCOMERCIAL
ON LECTOR.IDLOCALCOMERCIAL = LOCALCOMERCIAL.IDENTIFICADOR
WHERE RANK <= 20;


--RFC3 - MOSTRAR EL ÍNDICE DE AFORO DEL CENTRO COMERCIAL EN UNA FECHA

SELECT IDCENTROCOMERCIAL, ROUND(AVG(NUM_VISITAS/AFOROTOTAL),4) AS INDICE
FROM
(
    SELECT LECTOR.IDCENTROCOMERCIAL, HORA, MINUTO, COUNT(*) AS NUM_VISITAS
    FROM REGISTRANCARNET JOIN LECTOR
    ON REGISTRANCARNET.IDLECTOR = LECTOR.ID
    JOIN HORARIO
    ON REGISTRANCARNET.HORAENTRADA = HORARIO.ID
    WHERE FECHA =  TO_DATE('2018/12/01','yyyy/mm/dd') AND LECTOR.IDCENTROCOMERCIAL IS NOT NULL AND LECTOR.IDCENTROCOMERCIAL = 6
    GROUP BY LECTOR.IDCENTROCOMERCIAL, HORA, MINUTO
),
(
    SELECT SUM(AFORO) AS AFOROTOTAL
    FROM
    (
        (SELECT AFORO
        FROM
        ASCENSOR JOIN CAPACIDADNORMAL 
        ON ASCENSOR.CAPACIDADNORMAL = CAPACIDADNORMAL.ID
        WHERE ASCENSOR.IDCENTROCOMERCIAL = 6)
        UNION
        (SELECT AFORO
        FROM
        BANO JOIN CAPACIDADNORMAL 
        ON BANO.CAPACIDADNORMAL = CAPACIDADNORMAL.ID
        WHERE BANO.IDCENTROCOMERCIAL = 6)
        UNION
        (SELECT AFORO
        FROM
        LOCALCOMERCIAL JOIN AREA 
        ON LOCALCOMERCIAL.AREA = AREA.ID
        WHERE LOCALCOMERCIAL.IDCENTROCOMERCIAL = 6)
        UNION
        (SELECT AFORO
        FROM
        PARQUEADERO JOIN CAPACIDADNORMAL 
        ON PARQUEADERO.CAPACIDADNORMAL = CAPACIDADNORMAL.ID
        WHERE PARQUEADERO.IDCENTROCOMERCIAL = 6)
    )
)
GROUP BY IDCENTROCOMERCIAL;

--RFC3 - MOSTRAR EL ÍNDICE DE AFORO DEL CENTRO COMERCIAL EN UN RANGO DE FECHAS

SELECT IDCENTROCOMERCIAL, ROUND(AVG(NUM_VISITAS/AFOROTOTAL),4) AS INDICE
FROM
(
    SELECT LECTOR.IDCENTROCOMERCIAL, HORA, MINUTO, COUNT(*) AS NUM_VISITAS
    FROM REGISTRANCARNET JOIN LECTOR
    ON REGISTRANCARNET.IDLECTOR = LECTOR.ID
    JOIN HORARIO
    ON REGISTRANCARNET.HORAENTRADA = HORARIO.ID
    WHERE LECTOR.IDCENTROCOMERCIAL IS NOT NULL AND FECHA BETWEEN TO_DATE('2018/05/19','yyyy/mm/dd') AND TO_DATE('2020/07/20','yyyy/mm/dd') AND LECTOR.IDCENTROCOMERCIAL = 6
    GROUP BY LECTOR.IDCENTROCOMERCIAL, HORA, MINUTO
),
(
    SELECT SUM(AFORO) AS AFOROTOTAL
    FROM
    (
        (SELECT AFORO
        FROM
        ASCENSOR JOIN CAPACIDADNORMAL 
        ON ASCENSOR.CAPACIDADNORMAL = CAPACIDADNORMAL.ID
        WHERE ASCENSOR.IDCENTROCOMERCIAL = 6)
        UNION
        (SELECT AFORO
        FROM
        BANO JOIN CAPACIDADNORMAL 
        ON BANO.CAPACIDADNORMAL = CAPACIDADNORMAL.ID
        WHERE BANO.IDCENTROCOMERCIAL = 6)
        UNION
        (SELECT AFORO
        FROM
        LOCALCOMERCIAL JOIN AREA 
        ON LOCALCOMERCIAL.AREA = AREA.ID
        WHERE LOCALCOMERCIAL.IDCENTROCOMERCIAL = 6)
        UNION
        (SELECT AFORO
        FROM
        PARQUEADERO JOIN CAPACIDADNORMAL 
        ON PARQUEADERO.CAPACIDADNORMAL = CAPACIDADNORMAL.ID
        WHERE PARQUEADERO.IDCENTROCOMERCIAL = 6)
    )
)
WHERE IDCENTROCOMERCIAL IS NOT NULL
GROUP BY IDCENTROCOMERCIAL;

--RFC3 - MOSTRAR EL ÍNDICE DE AFORO DEL CENTRO COMERCIAL EN UN RANGO DE HORAS

SELECT IDCENTROCOMERCIAL, ROUND(AVG(NUM_VISITAS/AFOROTOTAL),4) AS INDICE
FROM
(
    SELECT LECTOR.IDCENTROCOMERCIAL, COUNT(*) AS NUM_VISITAS
    FROM REGISTRANCARNET JOIN LECTOR
    ON REGISTRANCARNET.IDLECTOR = LECTOR.ID
    JOIN HORARIO
    ON REGISTRANCARNET.HORAENTRADA = HORARIO.ID
    WHERE LECTOR.IDCENTROCOMERCIAL IS NOT NULL AND FECHA =  TO_DATE('2018/12/01','yyyy/mm/dd') AND LECTOR.IDCENTROCOMERCIAL = 6
    AND (HORA BETWEEN 10 AND 16) OR (HORA = 10 AND MINUTO >= 35) OR (HORA = 16 AND MINUTO <= 52)
    GROUP BY LECTOR.IDCENTROCOMERCIAL
),
(
    SELECT SUM(AFORO) AS AFOROTOTAL
    FROM
    (
        (SELECT AFORO
        FROM
        ASCENSOR JOIN CAPACIDADNORMAL 
        ON ASCENSOR.CAPACIDADNORMAL = CAPACIDADNORMAL.ID
        WHERE ASCENSOR.IDCENTROCOMERCIAL = 6)
        UNION
        (SELECT AFORO
        FROM
        BANO JOIN CAPACIDADNORMAL 
        ON BANO.CAPACIDADNORMAL = CAPACIDADNORMAL.ID
        WHERE BANO.IDCENTROCOMERCIAL = 6)
        UNION
        (SELECT AFORO
        FROM
        LOCALCOMERCIAL JOIN AREA 
        ON LOCALCOMERCIAL.AREA = AREA.ID
        WHERE LOCALCOMERCIAL.IDCENTROCOMERCIAL = 6)
        UNION
        (SELECT AFORO
        FROM
        PARQUEADERO JOIN CAPACIDADNORMAL 
        ON PARQUEADERO.CAPACIDADNORMAL = CAPACIDADNORMAL.ID
        WHERE PARQUEADERO.IDCENTROCOMERCIAL = 6)
    )
)
WHERE IDCENTROCOMERCIAL IS NOT NULL
GROUP BY IDCENTROCOMERCIAL;

--RFC3 - MOSTRAR EL ÍNDICE DE AFORO DEL LOCAL COMERCIAL EN UNA FECHA
SELECT LOCALCOMERCIAL.IDENTIFICADOR AS IDENTIFICADOR, ROUND(AVG(NUM_VISITAS/AREA.AFORO),4) AS INDICE
FROM LOCALCOMERCIAL
JOIN
    (
        SELECT LECTOR.IDLOCALCOMERCIAL, HORARIO.HORA, HORARIO.MINUTO, COUNT(*) AS NUM_VISITAS
        FROM REGISTRANCARNET 
        JOIN HORARIO
        ON REGISTRANCARNET.HORAENTRADA = HORARIO.ID
        JOIN LECTOR
        ON REGISTRANCARNET.IDLECTOR = LECTOR.ID
        WHERE FECHA =  TO_DATE('2019/07/19','yyyy/mm/dd') AND LECTOR.IDLOCALCOMERCIAL IS NOT NULL
        GROUP BY LECTOR.IDLOCALCOMERCIAL, HORARIO.HORA, HORARIO.MINUTO
    ) AUX
ON LOCALCOMERCIAL.IDENTIFICADOR = AUX.IDLOCALCOMERCIAL
JOIN AREA
ON LOCALCOMERCIAL.AREA = AREA.ID
WHERE LOCALCOMERCIAL.IDENTIFICADOR = 'LC101'
GROUP BY LOCALCOMERCIAL.IDENTIFICADOR;

--RFC3 - MOSTRAR EL ÍNDICE DE AFORO DEL LOCAL COMERCIAL EN UN RANGO DE FECHAS

SELECT LOCALCOMERCIAL.IDENTIFICADOR AS IDENTIFICADOR, ROUND(AVG(NUM_VISITAS/AREA.AFORO),4) AS INDICE
FROM LOCALCOMERCIAL
JOIN
    (
        SELECT LECTOR.IDLOCALCOMERCIAL, HORARIO.HORA, HORARIO.MINUTO, COUNT(*) AS NUM_VISITAS
        FROM REGISTRANCARNET 
        JOIN HORARIO
        ON REGISTRANCARNET.HORAENTRADA = HORARIO.ID
        JOIN LECTOR
        ON REGISTRANCARNET.IDLECTOR = LECTOR.ID
        WHERE FECHA BETWEEN TO_DATE('2019/05/19','yyyy/mm/dd') AND TO_DATE('2020/07/20','yyyy/mm/dd') AND LECTOR.IDLOCALCOMERCIAL IS NOT NULL
        GROUP BY LECTOR.IDLOCALCOMERCIAL, HORARIO.HORA, HORARIO.MINUTO
    ) AUX
ON LOCALCOMERCIAL.IDENTIFICADOR = AUX.IDLOCALCOMERCIAL
JOIN AREA
ON LOCALCOMERCIAL.AREA = AREA.ID
WHERE LOCALCOMERCIAL.IDENTIFICADOR = 'LC307'
GROUP BY LOCALCOMERCIAL.IDENTIFICADOR;


--RFC3 - MOSTRAR EL ÍNDICE DE AFORO DEL LOCAL COMERCIAL EN UN RANGO DE HORAS
SELECT LOCALCOMERCIAL.IDENTIFICADOR AS IDENTIFICADOR, ROUND(AVG(NUM_VISITAS/AREA.AFORO), 4) AS INDICE
FROM LOCALCOMERCIAL
JOIN
    (
        SELECT LECTOR.IDLOCALCOMERCIAL, COUNT(*) AS NUM_VISITAS
        FROM REGISTRANCARNET 
        JOIN HORARIO
        ON REGISTRANCARNET.HORAENTRADA = HORARIO.ID
        JOIN LECTOR
        ON REGISTRANCARNET.IDLECTOR = LECTOR.ID
        WHERE FECHA =  TO_DATE('2019/07/19','yyyy/mm/dd') AND 
        HORA BETWEEN 10 AND 20 OR (HORA = 10 AND MINUTO >= 00) OR (HORA = 20 AND MINUTO <= 47) AND LECTOR.IDLOCALCOMERCIAL IS NOT NULL 
        GROUP BY LECTOR.IDLOCALCOMERCIAL
    ) AUX
ON LOCALCOMERCIAL.IDENTIFICADOR = AUX.IDLOCALCOMERCIAL
JOIN AREA
ON LOCALCOMERCIAL.AREA = AREA.ID
WHERE LOCALCOMERCIAL.IDENTIFICADOR = 'LC305'
GROUP BY LOCALCOMERCIAL.IDENTIFICADOR;


--RFC3 - MOSTRAR EL ÍNDICE DE AFORO DEL TIPO DE LOCAL COMERCIAL EN UNA FECHA

SELECT INF_AFORO.TIPO AS IDENTIFICADOR, ROUND(AVG(INF_VISITAS.NUM_VISITAS/INF_AFORO.AFORO_TOTAL_TIPO),4) AS INDICE
FROM
(
    SELECT TIPOLOCAL.TIPO, SUM(AFORO) AS AFORO_TOTAL_TIPO
    FROM LOCALCOMERCIAL JOIN TIPOLOCAL
    ON LOCALCOMERCIAL.TIPOLOCAL = TIPOLOCAL.ID
    JOIN AREA
    ON LOCALCOMERCIAL.AREA = AREA.ID
    WHERE TIPOLOCAL.TIPO = 'Restaurante'
    GROUP BY TIPOLOCAL.TIPO
) INF_AFORO
JOIN
(
    SELECT TIPOLOCAL.TIPO, HORA, MINUTO, COUNT(*) AS NUM_VISITAS
    FROM REGISTRANCARNET JOIN LECTOR
    ON REGISTRANCARNET.IDLECTOR = LECTOR.ID
    JOIN LOCALCOMERCIAL
    ON LECTOR.IDLOCALCOMERCIAL = LOCALCOMERCIAL.IDENTIFICADOR
    JOIN TIPOLOCAL
    ON LOCALCOMERCIAL.TIPOLOCAL = TIPOLOCAL.ID
    JOIN HORARIO
    ON REGISTRANCARNET.HORAENTRADA = HORARIO.ID
    WHERE FECHA = TO_DATE('2019/07/19','yyyy/mm/dd') 
    AND UPPER(TIPOLOCAL.TIPO) = 'RESTAURANTE'
    GROUP BY TIPOLOCAL.TIPO, HORA, MINUTO
)INF_VISITAS
ON INF_AFORO.TIPO = INF_VISITAS.TIPO
GROUP BY INF_AFORO.TIPO;

--RFC3 - MOSTRAR EL ÍNDICE DE AFORO DEL TIPO DE LOCAL EN UN RANGO DE FECHAS
SELECT INF_AFORO.TIPO AS IDENTIFICADOR, ROUND(AVG(INF_VISITAS.NUM_VISITAS/INF_AFORO.AFORO_TOTAL_TIPO),4) AS INDICE
FROM
(
    SELECT TIPOLOCAL.TIPO, SUM(AFORO) AS AFORO_TOTAL_TIPO
    FROM LOCALCOMERCIAL JOIN TIPOLOCAL
    ON LOCALCOMERCIAL.TIPOLOCAL = TIPOLOCAL.ID
    JOIN AREA
    ON LOCALCOMERCIAL.AREA = AREA.ID
    AND UPPER(TIPOLOCAL.TIPO) = 'RESTAURANTE'
    GROUP BY TIPOLOCAL.TIPO
) INF_AFORO
JOIN
(
    SELECT TIPOLOCAL.TIPO, HORA, MINUTO, COUNT(*) AS NUM_VISITAS
    FROM REGISTRANCARNET JOIN LECTOR
    ON REGISTRANCARNET.IDLECTOR = LECTOR.ID
    JOIN LOCALCOMERCIAL
    ON LECTOR.IDLOCALCOMERCIAL = LOCALCOMERCIAL.IDENTIFICADOR
    JOIN TIPOLOCAL
    ON LOCALCOMERCIAL.TIPOLOCAL = TIPOLOCAL.ID
    JOIN HORARIO
    ON REGISTRANCARNET.HORAENTRADA = HORARIO.ID
    WHERE FECHA BETWEEN TO_DATE('2017/05/19','yyyy/mm/dd') AND TO_DATE('2021/07/20','yyyy/mm/dd')
    AND UPPER(TIPOLOCAL.TIPO) = UPPER ('Restaurante')
    GROUP BY TIPOLOCAL.TIPO, HORA, MINUTO
)INF_VISITAS
ON INF_AFORO.TIPO = INF_VISITAS.TIPO
GROUP BY INF_AFORO.TIPO;

--RFC3 - MOSTRAR EL ÍNDICE DE AFORO DEL TIPO DE LOCAL EN UN RANGO DE HORAS

SELECT INF_AFORO.TIPO AS IDENTIFICADOR, ROUND(AVG(INF_VISITAS.NUM_VISITAS/INF_AFORO.AFORO_TOTAL_TIPO),4) AS INDICE
FROM
(
    SELECT TIPOLOCAL.TIPO, SUM(AFORO) AS AFORO_TOTAL_TIPO
    FROM LOCALCOMERCIAL JOIN TIPOLOCAL
    ON LOCALCOMERCIAL.TIPOLOCAL = TIPOLOCAL.ID
    JOIN AREA
    ON LOCALCOMERCIAL.AREA = AREA.ID
    AND UPPER(TIPOLOCAL.TIPO) = 'RESTAURANTE'
    GROUP BY TIPOLOCAL.TIPO
) INF_AFORO
JOIN
(
    SELECT TIPOLOCAL.TIPO, HORA, MINUTO, COUNT(*) AS NUM_VISITAS
    FROM REGISTRANCARNET JOIN LECTOR
    ON REGISTRANCARNET.IDLECTOR = LECTOR.ID
    JOIN LOCALCOMERCIAL
    ON LECTOR.IDLOCALCOMERCIAL = LOCALCOMERCIAL.IDENTIFICADOR
    JOIN TIPOLOCAL
    ON LOCALCOMERCIAL.TIPOLOCAL = TIPOLOCAL.ID
    JOIN HORARIO
    ON REGISTRANCARNET.HORAENTRADA = HORARIO.ID
    WHERE FECHA = TO_DATE('2019/07/19','yyyy/mm/dd') AND HORA BETWEEN 12 AND 18
    OR (HORA = 12 AND MINUTO >= 35) OR (HORA = 18 AND MINUTO <= 10)
    AND TIPOLOCAL.TIPO = 'Restaurante'
    GROUP BY TIPOLOCAL.TIPO, HORA, MINUTO
)INF_VISITAS
ON INF_AFORO.TIPO = INF_VISITAS.TIPO
GROUP BY INF_AFORO.TIPO;
